supabase.url=https://swpzvmogscgddwocdlwv.supabase.co
supabase.anon.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cHp2bW9nc2NnZGR3b2NkbHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MjQxNTIsImV4cCI6MjA5NjUwMDE1Mn0.0ixPyns0UcqGrSnsQocCjzz5k_fQsbS0cJQoFu98Ujs
